#!/bin/bash



# ---------------- INIT ----------------

#cur exe dir
CXD=$(dirname $(readlink -f $0))
pCXD=$(dirname $CXD)




# ---------------- EXECUTION ----------------

#clean
rm --recursive --force $pCXD/tmp
